spring:
  datasource:
#    jdbc:mysql: //${MYSQL_HOST:localhost}:3305/erp
    username: mojo
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
    url:
      jdbc:mariadb://localhost:3306/erp
#      jdbc:mysql://${MYSQL_HOST:localhost}:3305/erp

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  thymeleaf:
    cache: false
server:
  error:
    include-message: always