spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/erp
    username: bs1041
    password: 4321
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  thymeleaf:
    cache: false
server:
  error:
    include-message: always