spring:
  datasource:
    username: root
    password: aUkUADiYTHCc8fK7OZHd
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
      jdbc:mysql://root:aUkUADiYTHCc8fK7OZHd@containers-us-west-38.railway.app:7797/railway

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  thymeleaf:
    cache: false
server:
  error:
    include-message: always